image: markhobson/maven-chrome:jdk-18

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

test:
  stage: test
  allow_failure: true

  # Run the tests
  script:
    - mvn compile "-Dtest=*" test

  # Store artifacts
  artifacts:
    when: always
    name: "report"
    paths:
      - target/surefire-reports/*
      - video/*
      - trace/*
      - screenshots/*
      - stats.xlsx
    expire_in: 1 h
